import clipboard
import pandas as pd
import pyautogui as py
from time import sleep
import pyperclip

df1 = pd.read_excel(r"C:\Users\Avantti\Desktop\VIVOCORP\ROBO\COLAR SEGUNDO - Copia.xlsx")
sleep(5)
for index, row in df1.iterrows():
    sleep(4)
    # Obtenção do número do CNPJ e formatação
    CNPJ = str(row['DOC'])
    py.click(267,289)
    sleep(3)
    py.click(283,313)
    sleep(3)
    py.click(475,360)
    sleep(3)
    py.click(616,428)
    sleep(3)
    py.write(CNPJ)
    sleep(3)

    py.click(349,363)
    sleep(3)
    py.click(1120,852)
    sleep(2)
    for i in range(6):
        py.click(1897,351)
        sleep(1)
    sleep(2)
    py.click(1216,449)
    sleep(3)
    py.click(840,504)
    sleep(.5)
    pyperclip.copy('')
    py.hotkey('ctrl','c')
    sleep(1)
    cpf = clipboard.paste()
    sleep(1)
    py.click(984,504)
    sleep(.5)
    pyperclip.copy('')
    py.hotkey('ctrl', 'c')
    sleep(1)
    nome = clipboard.paste()
    sleep(1)
    py.click(1102,504)
    sleep(.5)
    pyperclip.copy('')
    py.hotkey('ctrl', 'c')
    sleep(1)
    nome_do_meio = clipboard.paste()
    sleep(1)
    py.click(1250,504)
    sleep(.5)
    pyperclip.copy('')
    py.hotkey('ctrl', 'c')
    sleep(1)
    sobrenome = clipboard.paste()
    sleep(1)

    for c in range(3):
        py.click(1338,727)
        sleep(.8)

    py.click(1292,504)
    sleep(.5)
    pyperclip.copy('')
    py.hotkey('ctrl', 'c')
    sleep(1)
    telefone = clipboard.paste()
    sleep(1)
    for c in range(3):
        py.click(1338,727)
        sleep(.8)

    py.click(1292,504)
    sleep(.5)
    pyperclip.copy('')
    py.hotkey('ctrl', 'c')
    sleep(1)
    email = clipboard.paste()
    sleep(1)

    print(cpf, nome, nome_do_meio, sobrenome, telefone)
    py.click(1346,324)
    sleep(3)
    py.press('enter')
    sleep(1)
    py.click(882,1050)
    sleep(.5)
    py.click(535,258)
    sleep(.5)
    py.write(CNPJ)
    sleep(1)
    py.press('tab')
    sleep(.5)
    py.write(cpf)
    sleep(1)
    py.press('tab')
    sleep(.5)
    py.write(nome + " " + nome_do_meio + " " + sobrenome)
    sleep(1)
    py.press('tab')
    sleep(.5)
    py.write(telefone)
    sleep(1)
    py.press('tab')
    sleep(.5)
    py.write(email)
    sleep(1)
    py.click(1909,953)
    sleep(1)
    py.click(837,1045)

